FROM python:3.14-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.9.27 /uv /uvx /bin/

RUN apt-get update && apt-get install -y --no-install-recommends \
    libx11-6 libxrender1 libxtst6 libxi6 ffmpeg libsm6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN uv sync --locked

RUN mkdir -p /certs

CMD ["uv","run","main.py"]