{{- if and (not .Values.config.auth.existingSecret) .Values.config.auth.password -}}
{{- $secretName := printf "%s-secret" (include "dt4mob-sumo-simulator.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "dt4mob-sumo-simulator.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.config.auth.username | quote }}
  password: {{ .Values.config.auth.password | quote }}
{{- end }}